base_feedback:
    resource: "@FeedbacksBundle/Controller/FeedbackController.php"
    type:     annotation
    prefix:   /feedback

base_user_signal:
    resource: "@SignalBundle/Controller/UserSignalController.php"
    type:     annotation
    prefix:   /signal

#MEMBER ROUTES#
recommandation:
    resource: "@RecommandationBundle/Controller/RecommandationController.php"
    type:     annotation
    prefix:   /member/recommandations

experience:
    resource: "@ExperienceBundle/Controller/ExperienceController.php"
    type:     annotation
    prefix:   /member/experiences

event:
    resource: "@EventBundle/Controller/EventController.php"
    type:     annotation
    prefix:   /member/events

match:
    resource: "@MatchBundle/Controller/MatchController.php"
    type:     annotation
    prefix:   /member/matches

news_feed:
    resource: "@NewsFeedBundle/Controller/NewsFeedController.php"
    type:     annotation
    prefix:   /member/home

member:
    resource: "@MemberBundle/Controller/MemberController.php"
    type:     annotation
    prefix:   /member

#base:
#    resource: "@BaseBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
