service:
    resource: "@ServiceBundle/Controller/"
    type:     annotation
    prefix:   /

message:
    resource: "@MessageBundle/Resources/config/routing.xml"
    prefix:   /message

admin_question:
    resource: "@AdminQuestionBundle/Controller/"
    type:     annotation
    prefix:   /admin/questions

publicite:
    resource: "@PubliciteBundle/Controller/AdvertController.php"
    type:     annotation
    prefix:   /publicite
publicite_admin:
    resource: "@PubliciteBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /publiciteAdmin

admin_chart:
    resource: "@AdminChartBundle/Controller/"
    type:     annotation
    prefix:   /admin/charts

admin_business:
    resource: "@AdminBusinessBundle/Controller/"
    type:     annotation
    prefix:   /admin/businesses

admin_member:
    resource: "@AdminMemberBundle/Controller/"
    type:     annotation
    prefix:   /admin/members

admin_home:
    resource: "@AdminHomeBundle/Controller/"
    type:     annotation
    prefix:   /admin

business_chart:
    resource: "@BusinessChartBundle/Controller/"
    type:     annotation
    prefix:   /business/charts




business_advert:
    resource: "@BusinessAdvertBundle/Controller/BusinessAdvertController.php"
    type:     annotation
    prefix:   /business/adverts

business_event:
    resource: "@BusinessEventBundle/Controller/"
    type:     annotation
    prefix:   /business/events

business_home:
    resource: "@BusinessHomeBundle/Controller/"
    type:     annotation
    prefix:   /business

base_feedback:
    resource: "@FeedbacksBundle/Controller/FeedbackController.php"
    type:     annotation
    prefix:   /feedback

base_user_signal:
    resource: "@SignalBundle/Controller/UserSignalController.php"
    type:     annotation
    prefix:   /signal

#MEMBER ROUTES#
recommandation:
    resource: "@RecommandationBundle/Controller/RecommandationController.php"
    type:     annotation
    prefix:   /member/recommandations

experience:
    resource: "@ExperienceBundle/Controller/ExperienceController.php"
    type:     annotation
    prefix:   /member/experiences

event:
    resource: "@EventBundle/Controller/EventController.php"
    type:     annotation
    prefix:   /member/events

match:
    resource: "@MatchBundle/Controller/MatchController.php"
    type:     annotation
    prefix:   /member

news_feed:
    resource: "@NewsFeedBundle/Controller/NewsFeedController.php"
    type:     annotation
    prefix:   /member/home

member:
    resource: "@MemberBundle/Controller/"
    type:     annotation
    prefix:   /member

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /base

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /member

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register/{type}
    defaults: {type: 1}

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

business_login:
    path:  /business/login
    defaults: { _controller: BusinessFOSSecurityBundle:Security:login }

business_login_check:
    path:  /business/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

business_logout:
    path:  /business/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

admin_login:
    path:  /admin/login
    defaults: { _controller: AdminFOSSecurityBundle:Security:login }

admin_login_check:
    path:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /fosmessage

announce:
    path:  /admin/announce
    defaults: { _controller: AdminHomeBundle:Default:announce }