# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_BUSINESS: ROLE_BUSINESS
        ROLE_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
#        business:
#            pattern:            /business/(.*)
#            form_login:
#              provider:       fos_userbundle
#              login_path:     business_login
#              check_path:     business_login_check
#              default_target_path: business_home
#            logout:
#              path:           business_logout
#              target:         business_login
#            anonymous:        ~
#            context:          application
#        admin:
#            pattern:            /admin/(.*)
#            form_login:
#              provider:       fos_userbundle
#              login_path:     admin_login
#              check_path:     admin_login_check
#              default_target_path: admin_home
#            logout:
#              path:           admin_logout
#              target:         admin_login
#            anonymous:        ~
#            context:          application
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/business/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/business/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/business/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/member, role: ROLE_USER }
        - { path: ^/business, role: ROLE_BUSINESS }