<?php

namespace PubliciteBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSidePubDQL()
    {
        $q=$this->getEntityManager()->createQuery('select m from BaseBundle:Advert m where m.state=:state ')
        ->setParameter('state','1');
        return $q->getResult();
    }
    public function findBigPubDQL()
    {
        $q=$this->getEntityManager();
        $max = $q->createQuery('Select MAX(m.id) FROM BaseBundle:Advert m')->getSingleScalarResult();
        return $q->createQuery('select m from BaseBundle:Advert m where   m.id>=:rand
ORDER BY m.id ASC ')  ->setParameter('rand',rand(0,$max))
            ->setMaxResults(1)
            ->getResult();
    }
    public function findThisUserPubs($user)
    {
        $q=$this->getEntityManager()->createQuery('select m from BaseBundle:Advert m where m.business=:a ')
            ->setParameter('a',$user);
        return $q->getResult();

    }
    public function findPubsPourAdminDQL()
    {
        $q=$this->getEntityManager()->createQuery('select m from BaseBundle:Advert m where  m.endDate>=CURRENT_TIMESTAMP()')
         ;
        return $q->getResult();
    }

}
