<?php
/**
 * Created by PhpStorm.
 * User: vaider
 * Date: 03/04/2018
 * Time: 19:41
 */

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
namespace BaseBundle\Repository;
use Doctrine\ORM\EntityRepository;
class RatingRepository extends EntityRepository
{
    public function avgrating()
    {
        $query=$this->getEntityManager()->createQuery(
            "select c.idE , AVG(c.rating) AS avgrating from BaseBundle:Rating c
             Group BY c.idE  "
        );
        return $query->getResult();
    }

}